catalog/catalog/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

import debug_toolbar

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path('minerals/', include('minerals.urls', namespace='minerals')),
    path('admin/', admin.site.urls),
    path('', views.index, name='home'),
]

urlpatterns += staticfiles_urlpatterns()

catalog/minerals/urls.py
from django.urls import path, re_path

from . import views

app_name = 'minerals'
urlpatterns = [
    path('detail/<int:pk>/', views.mineral_detail, name='detail'),
    path('search/<str:term>/', views.search, name='search'),
    path('search_all/<str:term>/', views.search_in_all, name='search_all'),
    path('', views.index, name='index')
]

catalog/minerals/models.py
from django.db import models


class Mineral(models.Model):
    name = models.CharField(max_length=255)
    image_filename = models.CharField(max_length=255, null=True)
    image_caption = models.TextField(null=True)
    category = models.CharField(max_length=255, null=True)
    formula = models.TextField(null=True)
    strunz_classification = models.CharField(max_length=255, null=True)
    color = models.TextField(null=True)
    crystal_system = models.CharField(max_length=255, null=True)
    unit_cell = models.TextField(null=True)
    crystal_symmetry = models.CharField(max_length=255, null=True)
    cleavage = models.CharField(max_length=255, null=True)
    mohs_scale_hardness = models.CharField(max_length=255, null=True)
    luster = models.CharField(max_length=255, null=True)
    streak = models.CharField(max_length=255, null=True)
    diaphaneity = models.CharField(max_length=255, null=True)
    optical_properties = models.CharField(max_length=255, null=True)
    refractive_index = models.CharField(max_length=255, null=True)
    crystal_habit = models.TextField(blank=True)
    specific_gravity = models.CharField(max_length=255, null=True)
    group = models.CharField(max_length=255, null=True)

    def __str__(self):
        return self.name
    

catalog/catalog/views.py
import json

from django.shortcuts import render
from django.db.utils import OperationalError


def index(request):
    return render(request, 'home.html')

catalog/minerals/views.py
import random

from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, reverse
from django.db.models import Q, Count

from minerals.models import Mineral


def get_popular_fields(request, db, start=4):
    '''
        Get the most popular fields from a database as a list
    '''
    if not request.session.get('popular_fields'):
        fields = []
        for field in db._meta.get_fields()[start:]:
            count = db.objects.aggregate(
                field=Count(field.name, only=Q(field.name != "")))
            count_field = (count['field'], field.name)
            fields.append(count_field)
        fields.sort(reverse=True)
        request.session['popular_fields'] = [field for _, field in fields]
    return request.session.get('popular_fields')


def index(request):
    ''' 
        Render a page with the name of each mineral in the database
    '''
    return HttpResponseRedirect(reverse('minerals:search', kwargs={
        'term': 'A'
    }))


def mineral_detail(request, pk):
    '''
        Converts mineral model's attributes in a list
        and render them
    '''
    try:
        mineral_model = Mineral.objects.values().get(pk=pk)
    except Mineral.DoesNotExist:
        raise Http404
    popular_fields = get_popular_fields(request, Mineral)
    fields = [(key, mineral_model[key]) for key in popular_fields]
    return render(request,
                  'minerals/mineral_detail.html',
                  {'mineral': mineral_model,
                   'mineral_fields': fields})


def search(request, term):
    if len(term) == 1:
        minerals = Mineral.objects.filter(name__istartswith=term)
    else:
        minerals = Mineral.objects.filter(group__icontains=term)
        if not len(minerals):
            minerals = Mineral.objects.filter(color__icontains=term)
    return render(request, 'minerals/index.html', {
        'minerals': minerals,
        'term': term,
    })


def search_in_all(request, term):
    '''
        Search in all fields of the database
    '''
    term = request.GET.get('q')
    popular_fields = get_popular_fields(request, Mineral)
    list_queries = [Q(**{field + "__icontains": term})
                    for field in popular_fields]
    queries = Q(name__icontains=term)|Q(image_caption__icontains=term)
    for query in list_queries:
        queries = queries | query
    minerals = Mineral.objects.filter(queries)
    return render(request, 'minerals/index.html', {
        'minerals': minerals,
    })

catalog/minerals/templates/minerals/index.html
{% extends 'layout.html' %}
{% load mineral_extras %}

{% block title %}{{ block.super }} A magnificant catalog of minerals{% endblock %}

{% block content %}
<div class="grid-60 list__minerals">
    <ul class="minerals__container">
        {% for mineral in minerals %}
            <li class="minerals__item">
                <a class="minerals__anchor" href="{% url 'minerals:detail' pk=mineral.pk %}">
                    {{ mineral|truncatewords:1 }}
                </a>
            </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

catalog/minerals/templates/minerals/macros.html
{% for field in field_values %}
    {% if field %}
    <li>
        {% if term == field %}
        <a href="{% url 'minerals:search' term=field %}" class="active">
            {% if color %}
                <span title="{{ field }}" style="background-color: {{ field }};"></span>
            {% else %}
                {{ field }}
            {% endif %}
        </a>
        {% else %}
        <a href="{% url 'minerals:search' term=field %}" class="desactive">
            {% if color %}
                <span title="{{ field }}" style="background-color: {{ field }};"></span>
            {% else %}
                {{ field }}
            {% endif %}
        </a>
        {% endif %}
    </li>
    {% endif %}
{% endfor %}

catalog/minerals/templates/minerals/mineral_detail.html
{% extends 'layout.html' %}
{% load mineral_extras %}
{% load static from staticfiles %}

{% block title %}{{ block.super }} {{ mineral.name }}{% endblock %}

{% block static %}
<link rel="stylesheet" href="{% static 'css/detail.css' %}">
{% endblock %}

{% block content %}
<div class="grid-60 list__minerals">
    <div class="container__detail">
        <section>
            <h1 class="mineral__name">{{ mineral.name }}</h1>
            <div class="mineral__image-bg">
                <img class="mineral__image" src="{% static 'data/images/' %}{{ mineral.image_filename }}">
                <p class="mineral__caption">{{ mineral.image_caption }}</p>
            </div>
        </section>
        <div class="mineral__table-container">
            <table class="mineral__table">
            {% for name, value in mineral_fields %}
                {% if value %}
                    <tr>
                        <td class="mineral__category">{{ name|title|replace_for_spaces:'_' }}</td>
                        {% if name == 'formula' %}
                        <td class="mineral__formula">{{ value|markdown_to_html }}</td>
                        {% else %}
                        <td>{{ value|markdown_to_html }}</td>
                        {% endif %}
                    </tr>
                {% endif %}
            {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/home.html
{% load mineral_extras %}
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Macky's Minerals: Home</title>
  <meta name="description" content="">
  <meta name="author" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Cousine' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="{% static 'css/global.css' %}">
  <link rel="stylesheet" href="{% static 'css/home.css' %}">
</head>
<body>
    <div class="bounds">
        <div class="grid-100">
            <a href="{% url 'minerals:index' %}">
                <svg class="logo" viewBox="0 0 127.6 84.8" preserveAspectRation="xMinYMin meet">
                    <polygon points="42.7,84.8 49.6,79.4 40,62.5 51.2,43.5 51.2,43.5 25,0 0,55.6 "/>
                    <polygon class="logo--middle" points="52.9,79.5 52.9,79.5 84.8,80.1 59.7,35 43.3,62.4 "/>
                    <polygon points="127.6,61.4 127.6,61.4 110.3,13.5 110.3,13.5 70.3,48.1 70.3,48.1 88.3,80.5 95.3,81.4 95.3,81.4 "/>
                </svg>
                <h1 class="logo__name text-centered">Macky's Minerals</h1>
            </a>
            <p class="logo__text text-centered">They're not rocks!</p>
        </div>
        <div class="grid-100">
            <section>
                <p class="text-centered">New content soon!!</p>
            </section>
            <div class="option__home">
                <a class="minerals_option" href="{% url 'minerals:index' %}">See Catalog</a>
            </div>
            
        </div>
    </div>
    <div class="random__option">
    </div>
</body>
<html>

catalog/templates/layout.html
{% load static from staticfiles %}
{% load mineral_extras %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}Macky's Minerals:{% endblock %}</title>
  <meta name="description" content="">
  <meta name="author" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Cousine' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="{% static 'css/global.css' %}">
  <link rel="stylesheet" href="{% static 'css/custom.css' %}">
  {% block static %}{% endblock %}
</head>
<body>
    <nav class="top-bar-right">
        <a href="{% url 'home' %}">Home</a>
        <section class="search">
            <form action="{% url 'minerals:search_all' term='searching' %}" method="GET">
                <ul class="menu">
                    <li><input type="search" name="q" class="input__search"></li>
                    <li><button type="submit" class="button">Search</button></li>
                </ul>
            </form>
        </section>
    </nav>
    <div class="bounds">
        <div class="grid-100">
            <a href="{% url 'minerals:index' %}">
                <svg class="logo" viewBox="0 0 127.6 84.8" preserveAspectRation="xMinYMin meet">
                    <polygon points="42.7,84.8 49.6,79.4 40,62.5 51.2,43.5 51.2,43.5 25,0 0,55.6 "/>
                    <polygon class="logo--middle" points="52.9,79.5 52.9,79.5 84.8,80.1 59.7,35 43.3,62.4 "/>
                    <polygon points="127.6,61.4 127.6,61.4 110.3,13.5 110.3,13.5 70.3,48.1 70.3,48.1 88.3,80.5 95.3,81.4 95.3,81.4 "/>
                </svg>
                <h1 class="logo__name text-centered">Macky's Minerals</h1>
            </a>
            <p class="logo__text text-centered">They're not rocks!</p>
        </div>

        {% block alphabet %}
        <ul class="grid-100 alphabet">
            {% include "minerals/macros.html" with field_values="ABCDEFGHIJKLMNOPQRSTUVWXYZ" %}
        </ul>
        {% endblock %}
    </div>
    <div class="mineral__list">
        <div class="grid-20">
            <section>
                <h2>Groups</h2>
                <ul class="py_groups">
                    {% minerals_groups param='group' as groups %}
                    {% include "minerals/macros.html" with field_values=groups color=None %}
                </ul>
            </section>
        </div>
        {% block content %}{% endblock %}
        <div class="grid-20">
            <section>
                <h2>Colors</h2>
                <ul class="py_colors">
                    {% minerals_colors as colors %}
                    {% include "minerals/macros.html" with field_values=colors color=True %}
                </ul>
            </section>
        </div>
    </div>
    <div class="minerals__random">
        {% random_number as number %}
        <a class="minerals__anchor" href="{% url 'minerals:detail' pk=number %}">
            Show random mineral
        </a>
    </div>
</body>
<html>